---
# Configuration of the Cycloid stack
version: '4'
name: 'AWS EC2 Instance'
canonical: stack-compute-aws-demo
author: Cycloid
description: |
  Deploys an AWS EC2 instance using Terraform.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/aws-ec2.svg
keywords:
  - ec2
  - virtual machine
  - instance
  - provider:aws
technologies:
- technology: terraform
  version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform/main.tf'