---
# Configuration of the Cycloid stack
version: '4'
name: 'Azure Resource Group'
canonical: stack-resource-group-demo
author: Cycloid
description: |
  Deploy and manage Azure Resource Groups with configurable settings and tags.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/azure-resource-group.png
keywords:
  - resource-group
  - azure
  - provider:azure
technologies:
- technology: terraform
  version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .config_root $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .config_root $)/terraform/main.tf' 