---
version: "2"
use_cases:
- name: default
  sections:
  - name: Resource Group
    groups:
    - name: Resource Group Configuration
      technologies: [terraform]
      vars:
      - name: "Resource Group Name"
        description: "Name of the Azure resource group to create"
        key: resource_group_name
        widget: simple_text
        type: string
        required: true
        validations:
        - regexp: "^[a-zA-Z0-9-_()]{1,90}$"
          error_message: "Must be 1-90 characters long and contain only alphanumeric characters, hyphens, underscores, and parentheses."

      - name: "Azure Location"
        description: "Azure region to deploy the resource group"
        key: azure_location
        widget: auto_complete
        type: string
        default: "West Europe"
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/azure-locations.json
        required: true

      - name: "Custom Tags"
        description: "Enable custom tags for the resource group"
        key: enable_custom_tags
        widget: switch
        type: boolean
        default: false

    - name: Custom Tags
      technologies: [terraform]
      condition: "enable_custom_tags == true"
      vars:
      - name: "Tags"
        description: "Custom tags to apply to the resource group"
        key: custom_tags
        widget: text_area
        type: string
        default: |
          {
            "Environment": "production",
            "Department": "IT"
          }
        required: true

    - name: Azure Credentials
      technologies: [pipeline]
      vars:
      - name: "Azure Credentials"
        description: "The Azure credentials to use for deployment"
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true 