---
version: "2"
use_cases:
- name: outscale
  sections:
  - name: K3s
    groups:
    - name: Outscale Access
      technologies: [pipeline]
      vars:
      - name: "Outscale Account"
        description: "The Outscale account where to deploy the infrastructure."
        key: outscale_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: "((outscale))"
        required: true

      - name: "Outscale Region"
        description: "The Outscale region where to deploy the infrastructure."
        key: outscale_region
        widget: auto_complete
        type: string
        required: true
        default: "eu-west-2"
        values:
        - eu-west-2
        - cloudgouv-eu-west-1
        - us-east-2
        - us-west-1
        - ap-northeast-1

    - name: Outscale Infrastructure
      technologies: [terraform]
      vars:
      - name: "CPU"
        description: "The number of CPU to deploy."
        key: outscale_cpu
        widget: slider_range
        type: integer
        required: true
        default: 2
        values:
        - 1
        - 4
      - name: "Memory"
        description: "The amount of memory to deploy."
        key: outscale_mem
        widget: slider_range
        type: integer
        required: true
        default: 4
        values:
        - 1
        - 8

    - name: Outscale Networks
      technologies: [terraform]
      vars:
      - name: "Outscale Private Network"
        description: "Whether to connect to an Outscale private network."
        key: outscale_private_network
        widget: switch
        type: boolean
        required: true
        default: false

    - name: Outscale Private Network
      technologies: [terraform]
      condition: '$outscale_private_network == true'
      vars:
      - name: "Outscale Private Network"
        description: "Select an Outscale private network to connect the instance to."
        key: outscale_net
        widget: cy_inventory_resource
        widget_config:
          attribute: id
          filters:
            type: outscale_net
        type: string
        required: true


- name: ionos
  sections:
  - name: K3s cluster
    groups:
    - name: IONOS Access
      technologies: [pipeline]
      vars:
      - name: "IONOS Account"
        description: "The IONOS account where to deploy the infrastructure."
        key: ionos_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: "((ionos))"
        required: true

      - name: "IONOS Region"
        description: "The IONOS region where to deploy the infrastructure."
        key: ionos_region
        widget: dropdown
        type: map
        required: true
        values:
        - {"label": "Frankfurt am Main (DE)", "value": "de/fra"}
        - {"label": "Karlsruhe (DE)", "value": "de/fkb"}
        - {"label": "Berlin (DE)", "value": "de/txl"}
        - {"label": "Paris (FR)", "value": "fr/par"}
        - {"label": "London (GB)", "value": "gb/lhr"}
        - {"label": "Logroño (ES)", "value": "es/vit"}

    - name: IONOS Infrastructure
      technologies: [terraform]
      vars:
      - name: "IONOS Compute Configuration"
        description: "The IONOS cube configuration to deploy."
        key: ionos_cube
        widget: dropdown
        type: string
        required: true
        values:
        - "Basic Cube XS"
        - "Basic Cube S"
        - "Basic Cube M"
        - "Basic Cube L"
        - "Basic Cube XL"
        - "Memory Cube S"
        - "Memory Cube M"
        - "Memory Cube L"
        - "Memory Cube XL"

    - name: IONOS Networks
      technologies: [terraform]
      vars:
      - name: "IONOS Private Network"
        description: "Whether to connect the instance to a IONOS private network."
        key: ionos_private_network
        widget: switch
        type: boolean
        required: true
        default: false

    - name: IONOS Private Network
      technologies: [terraform]
      condition: '$ionos_private_network == true'
      vars:
      - name: "IONOS Private Network"
        description: "Select an IONOS private network to connect the instance to."
        key: ionos_lan
        widget: cy_inventory_resource
        widget_config:
          attribute: id
          filters:
            type: ionoscloud_lan
        type: string
        required: true