---
# Configuration of the Cycloid stack
version: '4'
name: 'ArgoCD'
canonical: stack-argocd
author: Cycloid
description: |
  Deploy ArgoCD on a Kubernetes cluster and create its GitHub repository.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/argocd.svg
keywords:
  - kubernetes
  - argocd
  - provider:kubernetes
technologies:
- technology: terraform
  version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .org $)/($ .project $)/($ .env $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .org $)/($ .project $)/($ .env $)/($ .component $)/terraform/main.tf'