---
version: "2"
use_cases:
- name: default
  sections:
  - name: S3
    groups:
    - name: S3 Configuration
      technologies: [terraform]
      vars:
      - name: "Bucket Name"
        description: "Name of the S3 bucket to create"
        key: bucket_name
        widget: simple_text
        type: string
        required: true
        validations:
        - regexp: "^[a-z0-9][a-z0-9.-]*[a-z0-9]$"
          error_message: "Must be 3 to 63 alphanumeric, dots, and hyphens chars."

      - name: "Versioning"
        description: "Enable versioning for the bucket"
        key: versioning_enabled
        widget: switch
        type: boolean
        default: true

      - name: "Custom Lifecycle Rules"
        description: "Configure custom lifecycle rules for the bucket"
        key: custom_lifecycle_rules
        widget: switch
        type: boolean
        default: false

    - name: Lifecycle Rules
      technologies: [terraform]
      condition: "custom_lifecycle_rules == true"
      vars:
      - name: "Lifecycle Rules"
        description: "Configure lifecycle rules for the bucket"
        key: lifecycle_rules
        widget: text_area
        type: string
        default: |
          [
            {
              "id": "transition-to-ia",
              "enabled": true,
              "prefix": "",
              "tags": {},
              "transition": [
                {
                  "days": 90,
                  "storage_class": "STANDARD_IA"
                }
              ]
            }
          ]

    - name: AWS
      technologies: [pipeline]
      vars:
      - name: "AWS Account"
        description: "The AWS account where to deploy the infrastructure. It contains access key and secret key."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true

      - name: "AWS Region"
        description: "AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        default: "eu-west-1"
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-regions.json
        required: true
