version: '3'
name: 'My Compute Instance'
canonical: 'my_compute_instance'
description: 'Deploys one instance using Terraform.'
author: 'cycloid_olivier'
image: 'https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png'
status: 'private'
template: false
keywords:
  - terraform
  - provider:aws
technologies:
  - technology: terraform
    version: 1.8.3
config:
  aws:
    name: 'AWS'
    description: 'Deploys a single AWS instance'
    cloud_provider: aws
    # Pipeline and variable configuration for the AWS CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .project $)/pipeline/($ .environment $)/variables.yml'
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/aws/main.tf'
        destination: '($ .project $)/terraform/aws/($ .environment $)/main.tf'
