---
version: "2"
use_cases:
- name: 'aws'
  sections:
  - name: Instance
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:

      - name: "AWS account"
        description: "The AWS account where to deploy the infrastructure. Create an AWS credential beforehand."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true
      - name: "AWS region"
        description: "AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-regions.json
        default: eu-west-1
        required: true


    - name: Virtual machine specifications
      technologies: [terraform]
      vars:

      - name: "Instance type"
        description: "Instance type for the VM."
        key: vm_instance_type
        widget: slider_list
        type: string
        default: "t3a.medium"
        values:
            - "t3a.small"
            - "t3a.medium"
            - "t3a.large"
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size for the VM."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 30
        values:
            - 30
            - 100
        required: true

        
    - name: Networking
      technologies: [terraform]
      vars:

      - name: "VPC"
        description: "VPC where to deploy the ec2 instance."
        key: vpc_id
        widget: simple_text
        type: string
        required: true
