---
# Service
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
spec:
  selector:
    app: ${APP_NAME}
  ports:
    - port: 80
      targetPort: ${APP_PORT}
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
spec:
  replicas: ${APP_REPLICAS}
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          image: ${APP_IMAGE_REPO}:${APP_IMAGE_TAG}
          ports:
            - containerPort: ${APP_PORT}
          imagePullPolicy: Always
---
# Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APP_NAME}
spec:
  rules:
    - host: ${APP_NAME}.${K8S_EXTERNAL_IP}.nip.io
      http:
        paths:
          - backend:
              serviceName: ${APP_NAME}
              servicePort: 80


apply with:
envsubst < deployment.yaml | kubectl apply -f -
