---
version: "2"
use_cases:
- name: default
  sections:
  - name: VMware Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "VMware Account"
        description: "The VMware account where to deploy the infrastructure. It contains vSphere username and password."
        key: vmware_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - vmware
        type: string
        default: "((vmware))"
        required: true

    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "vCPU"
        unit: vCPU
        description: "Number of vCPU allocated to the virtual machine."
        key: vm_cpu
        widget: slider_range
        type: integer
        default: 2
        values:
            - 1
            - 4
        required: true
        quota_config:
          type: "cpu"
      - name: "Memory"
        unit: Mo
        description: "Memory allocated to the virtual machine."
        key: vm_memory
        widget: slider_list
        type: integer
        default: 2048
        values:
            - 1024
            - 2048
            - 4096
        required: true
        quota_config:
          type: "memory"
      - name: "Disk"
        unit: Go
        description: "Disk size allocated to the virtual machine."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 10
            - 200
        required: true
        quota_config:
          type: "storage"