---
version: "2"
use_cases:
- name: default
  sections:
  - name: Nexus Repository
    groups:
    - name: Application Git
      technologies: [pipeline]
      vars:
      - name: "Application Git URL"
        description: "Git URL where the application is stored."
        key: git_url
        widget: simple_text
        type: string
        default: "git@github.com:"
        required: true

      - name: "Application Git Branch"
        description: "Git branch where the application is stored."
        key: git_branch
        widget: auto_complete
        type: string
        values: ["develop", "main", "master"]
        default: "main"
        required: true

      - name: "SSH Key"
        description: "The SSH private key to access the git repository."
        key: git_ssh_key
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - ssh
        type: string
        default: "((($ .project $)-($ .env $)-git-ssh.ssh_key))"
        required: true

    - name: Database
      technologies: [pipeline]
      vars:
      - name: "Database Engine"
        description: "Select the database engine that Prisma will connect to."
        key: database_engine
        widget: radios
        required: true
        type: map
        values:
        - {label: "PostgreSQL", value: "postgresql"}
        - {label: "MySQL", value: "mysql"}
        - {label: "None", value: ""}
        default: "PostgreSQL"
      - name: "Managed Database Provider"
        description: "Select the database engine that Prisma will connect to."
        key: database_cloud
        widget: radios
        required: true
        type: map
        values:
        - {label: "AWS RDS", value: "aws"}
        - {label: "Azure Managed Database", value: "azure"}
        default: "AWS RDS"
    - name: AWS RDS Selection
      technologies: [pipeline]
      condition: "database_cloud=='AWS RDS'"
      vars:
      - name: "AWS RDS"
        description: "Select the AWS RDS instance that Prisma will connect to."
        key: database_aws
        widget: cy_inventory_resource
        widget_config:
          attribute: id
          filters:
            type: aws_db_instance
            project: ($ .project $)
            environment: ($ .env $)
        required: true
        type: string
    - name: Azure Managed Database Selection
      technologies: [pipeline]
      condition: "database_cloud=='Azure Managed Database'"
      vars:
      - name: "Azure Managed Database"
        description: "Select the Azure Managed Database that Prisma will connect to."
        key: database_azure
        widget: cy_inventory_resource
        widget_config:
          attribute: id
          filters:
            type: azurerm_postgresql_server
            project: ($ .project $)
            environment: ($ .env $)
        required: true
        type: string

    - name: Kubernetes Test Cluster
      technologies: [pipeline]
      vars:
      - name: "Kubeconfig"
        description: "The Kubeconfig to access your Kubernetes Cluster."
        key: kubeconfig_content
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: ((custom_($ .project $)-($ .env $)-kubeconfig.kubeconfig))
        required: true
