---
version: "2"
use_cases:
- name: default
  sections:
  - name: config
    groups:
    - name: Scaffolding Template
      technologies: [pipeline]
      vars:
      - name: "Development Stack"
        description: "Select a scaffolding template according to your desired development stack."
        key: git_source_path
        widget: dropdown
        required: true
        type: map
        values:
        - {label: "REST API using Express and Prisma Client", value: "express"}
        - {label: "REST API using Fastify and Prisma Client", value: "fastify"}
        - {label: "REST API using hapi and Prisma Client", value: "hapi"}
        - {label: "REST API using Koa and Prisma Client", value: "koa"}
        - {label: "REST API using NestJS and Prisma Client", value: "nest"}
        - {label: "Web app using Next.js and Prisma Client", value: "nextjs"}
        - {label: "Fullstack app with Nuxt using Vue and Prisma Client", value: "nuxt"}
        - {label: "Web app using React Router 7 and Prisma ORM", value: "react-router-7"}
        - {label: "Simple NodeJS WebApp", value: "simple-counter"}
        default: "Simple NodeJS WebApp"
