---
version: "2"
use_cases:
- name: default
  sections:
  - name: config
    groups:
    - name: Git Repository Creation
      technologies: [pipeline]
      vars:
      - name: "GitHub PAT"
        description: "GitHub Personal Access Token allowing to create the new code repository"
        key: github_pat
        widget: cy_cred
        widget_config:
          cred_types: ["custom"]
        type: string
        default: "((github-pat.key))"
        required: true
    - name: Git Repository
      technologies: [pipeline]
      vars:
      - name: "Git Repository"
        description: "Git repository URL to copy for the first commit."
        key: git_source_url
        widget: simple_text
        type: string
        default: "https://github.com/cycloid-community-catalog/onboarding-scaffold.git"
        required: true
      - name: "Git Path"
        description: "Path in the Git repository to copy for the first commit."
        key: git_source_path
        widget: simple_text
        type: string
        default: "simple-counter"
        required: false