groups:
- name: overview
  jobs:
    - deploy-k3s

- name: destroy
  jobs:
    - destroy-k3s


jobs:
  - name: deploy-k3s
    serial: true
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - task: deploy-k3s
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          path: /bin/bash
          args:
          - -ec
          - |
            mkdir -p ~/.ssh
            echo "${SSH_PRIVATE_KEY}" >~/.ssh/git
            chmod 600 ~/.ssh/git
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/git
        params:
          SSH_PRIVATE_KEY: ((ssh_key))
          CLOUD_TYPE: ((cloud_type))
          IONOS_IP: ((ionos_ip))
          OUTSCALE_IP: ((outscale_ip))
          OTHER_IP: ((other_ip))
          CY_API_KEY: ((cycloid_api_key))
          CY_API_URL: ($ .api_url $)
          CY_ORG: ($ .organization_canonical $)
          PROJECT: ($ .project $)
          ENV: ($ .environment $)


  # Destroy the infrastructure
  - name: destroy-k3s
    serial: true
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - task: destroy-k3s
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          path: /bin/bash
          args:
          - -ecx
          - |
            echo "Deleting Credential ${CY_ORG}-${PROJECT}-${ENV}-kubeconfig"
            if ! cy credential delete --canonical "${CY_ORG}-${PROJECT}-${ENV}-kubeconfig"; then
              echo "Error: cy returned code $?
              exit 1
            fi
        params:
          CY_API_KEY: ((cycloid_api_key))
          CY_API_URL: ($ .api_url $)
          CY_ORG: ($ .organization_canonical $)
          PROJECT: ($ .project $)
          ENV: ($ .environment $)