---
version: "2"
use_cases:
- name: aws
  sections:
  - name: Amazon Relational Database Service (RDS)
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "AWS Account"
        description: "The AWS account where to deploy the infrastructure."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true
      - name: "AWS Region"
        description: "AWS region where to deploy the resources."
        key: aws_region
        widget: auto_complete
        type: string
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-regions.json
        default: eu-west-1
        validations: 
        - regexp: "^[a-z]{2}-[a-z]+-\\d+$" 
          error_message: "Please enter a valid AWS region such as us-east-1"
        required: true

    - name: RDS Configuration
      technologies: [terraform]
      vars:
      - name: "PostgreSQL Engine Version"
        description: "Version of the PostgreSQL engine."
        key: rds_engine_version
        widget: auto_complete
        type: string
        default: "17.4"
        values: ["17.4","17.3","17.2","17.1","16.8","16.7","16.6","16.5","16.4","16.3","16.2","16.1","16.0"]
        required: true
      - name: "Instance Class"
        description: "Instance class for the RDS instance."
        key: rds_instance_class
        widget: slider_list
        type: string
        default: "db.t4g.small"
        values:
            - "db.t4g.micro"
            - "db.t4g.small"
            - "db.t4g.medium"
        required: true
      - name: "Allocated Storage"
        unit: Go
        description: "The amount of allocated storage."
        key: rds_allocated_storage
        widget: slider_range
        type: integer
        default: 20
        values:
            - 10
            - 100
        required: true
      # - name: "Snapshot Identifier"
      #   description: "(Optional) Specifies whether or not to create this database from a snapshot. This corresponds to the snapshot ID you'd find in the RDS console, e.g: rds:production-2015-06-26-06-05."
      #   key: rds_snapshot_identifier
      #   widget: simple_text
      #   type: string
      #   required: false
      # - name: "Security Group"
      #   description: "The application security group to grant access to the database."
      #   key: app_security_group_id
      #   type: "string"
      #   widget: cy_inventory_resource
      #   widget_config:
      #     attribute: id
      #     filters:
      #       type: aws_security_group

      - name: "Create or Select Subnet"
        description: "Whether to create a new VPC and Subnet or select an existing Subnet."
        key: res_selector
        widget: dropdown
        type: map
        required: true
        default: "Create new"
        values:
        - {"label": "Create new", "value": "create"}
        - {"label": "Select from Asset Inventory", "value": "inventory"}
        - {"label": "Enter manually", "value": "manual"}

    - name: Select from Asset Inventory
      technologies: [terraform]
      condition: '$res_selector == "Select from Asset Inventory"'
      vars:
      - name: "Subnet"
        description: "Subnets where to deploy the resources. Make sure you select at least 2 subnets from different AZ but in the same region."
        key: rds_subnet_ids_inventory
        widget: cy_inventory_resource
        widget_config:
          attribute: id
          filters:
            type: aws_subnet
            attributes: 'availability_zone[rlike]=${aws_region}'
        validations:
          - array:
              min_elems: 2
            error_message: "At least two subnets must be selected"
        type: array
        required: true

    - name: Enter manually
      technologies: [terraform]
      condition: '$res_selector == "Enter manually"'
      vars:
      - name: "Subnet ID"
        description: "Subnet IDs where to deploy the resources. Make sure you enter at least 2 subnets from different AZ but in the same region."
        key: rds_subnet_ids_manual
        widget: text_area
        type: string
        required: true

    - name: Day-2 Operations
      technologies: [pipeline]
      vars:
      - name: "Destroy Timer"
        description: "The number of minutes to wait before automatically destroying the infrastructure after creation."
        key: destroy_timer_in_minutes
        widget: number
        type: integer
        default: 60
        required: true


- name: azure
  sections:
  - name: Database
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure credentials"
        description: "The azure credential used to deploy the infrastructure. It contains subscription_id, tenant_id, client_id, and client_secret."
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true

    - name: Database Configuration
      technologies: [terraform]
      vars:
      - name: "Server Name"
        description: "Name of the PostgreSQL Flexible Server."
        key: server_name
        widget: simple_text
        type: string
        default: "($ .project $)-($ .env $)"
        required: true
      - name: "PostgreSQL Version"
        description: "Version of PostgreSQL to use."
        key: postgresql_version
        widget: dropdown
        type: string
        default: "14"
        values: ["14","13","12","11"]
        required: true
      - name: "SKU Name"
        description: "SKU name for the PostgreSQL Flexible Server."
        key: sku_name
        widget: auto_complete
        type: string
        values:
        - "B_Standard_B1ms"
        - "B_Standard_B2s"
        - "B_Standard_B2ms"
        default: "B_Standard_B1ms"
        required: true
      - name: "Storage Size"
        description: "Storage size in MB."
        key: storage_mb
        widget: dropdown
        type: map
        default: "32 GB"
        values:
        - {"label": "32 GB", "value": 32768}
        - {"label": "64 GB", "value": 65536}
        - {"label": "128 GB", "value": 131072}
        - {"label": "256 GB", "value": 262144}
        - {"label": "512 GB", "value": 524288}
        - {"label": "1 TB", "value": 1048576}
        required: true
      - name: "Backup Retention Days"
        description: "Backup retention days."
        key: backup_retention_days
        widget: number
        type: integer
        default: 7
        required: true
      - name: "Enable Geo-Redundant Backups"
        description: "Enable geo-redundant backups."
        key: geo_redundant_backup_enabled
        widget: switch
        type: boolean
        default: false
        required: true
      - name: "Administrator Login"
        description: "Administrator login for PostgreSQL server."
        key: administrator_login
        widget: simple_text
        type: string
        default: "psqladmin"
        required: true
      - name: "Database Name"
        description: "Name of the database to create."
        key: database_name
        widget: simple_text
        type: string
        default: "($ .project $)-($ .env $)"
        required: true
      - name: "Azure Location"
        description: "Azure location."
        key: azure_location
        widget: auto_complete
        type: string
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/azure-locations.json
        default: "West Europe"
        required: true
      - name: "Create or Select Resource Group"
        description: "Whether to create a new Resource group or select existing ones."
        key: res_selector
        widget: dropdown
        type: map
        required: true
        default: "Create new"
        values:
        - {"label": "Create new", "value": "create"}
        - {"label": "Select from Asset Inventory", "value": "inventory"}
        - {"label": "Enter manually", "value": "manual"}
    - name: Select from Asset Inventory
      technologies: [terraform]
      condition: '$res_selector == "Select from Asset Inventory"'
      vars:
      - name: "Existing Resource Group Name"
        description: "The name of the existing resource group where the resources will be deployed."
        key: resource_group_name_inventory
        widget: cy_inventory_resource
        widget_config:
          attribute: name
          filters:
            type: azurerm_resource_group
        type: string
        required: true
    - name: Enter manually
      technologies: [terraform]
      condition: '$res_selector == "Enter manually"'
      vars:
      - name: "Resource Group Name"
        description: "The name of the existing resource group where the resources will be deployed."
        key: resource_group_name_manual
        widget: simple_text
        type: string
        required: true