---
version: "2"
use_cases:
- name: default
  sections:
  - name: K3s
    groups:
    - name: Target Cloud
      technologies: [pipeline]
      vars:
      - name: "Target Cloud"
        description: "The cloud hosting the instance where to install K3s."
        key: cloud_type
        widget: dropdown
        type: string
        required: true
        values:
        - "AWS"
        - "Azure"
        - "GCP"
        - "Ionos"
        - "Outscale"
        - "Other"

    - name: AWS Infrastructure
      technologies: [pipeline]
      condition: '$cloud_type == "AWS"'
      vars:
      - name: "AWS Instance"
        description: "The AWS instance where to install K3s."
        key: aws_ip
        widget: cy_inventory_resource
        widget_config:
          attribute: public_ip
          filters:
            type: aws_instance
            project: ($ .project $)
        type: string
        required: true

    - name: Azure Infrastructure
      technologies: [pipeline]
      condition: '$cloud_type == "Azure"'
      vars:
      - name: "Azure Instance"
        description: "The Azure instance where to install K3s."
        key: azure_ip
        widget: cy_inventory_resource
        widget_config:
          attribute: public_ip_address
          filters:
            type: azurerm_linux_virtual_machine
            project: ($ .project $)
        type: string
        required: true

    - name: GCP Infrastructure
      technologies: [pipeline]
      condition: '$cloud_type == "GCP"'
      vars:
      - name: "GCP Instance"
        description: "The GCP instance where to install K3s."
        key: gcp_ip
        widget: cy_inventory_resource
        widget_config:
          attribute: public_ip
          filters:
            type: google_compute_instance
            project: ($ .project $)
        type: string
        required: true

    - name: Ionos Infrastructure
      technologies: [pipeline]
      condition: '$cloud_type == "Ionos"'
      vars:
      - name: "Ionos Instance"
        description: "The Ionos instance where to install K3s."
        key: ionos_ip
        widget: cy_inventory_resource
        widget_config:
          attribute: primary_ip
          filters:
            type: ionoscloud_server
            project: ($ .project $)
        type: string
        required: true

    - name: Outscale Infrastructure
      technologies: [pipeline]
      condition: '$cloud_type == "Outscale"'
      vars:
      - name: "Outscale Instance"
        description: "The Outscale instance where to install K3s."
        key: outscale_ip
        widget: cy_inventory_resource
        widget_config:
          attribute: public_ip
          filters:
            type: outscale_vm
            project: ($ .project $)
        type: string
        required: true

    - name: Other Infrastructure
      technologies: [pipeline]
      condition: '$cloud_type == "Other"'
      vars:
      - name: "IP Address"
        description: "The IP address of the instance where to install K3s."
        key: other_ip
        widget: simple_text
        type: string
        required: true
        validations: 
        - regexp: "^\\d+\\.\\d+\\.\\d+\\.\\d+$" 
          error_message: "Please enter a valid IPv4 address such as 1.2.3.4"

    - name: SSH Key
      technologies: [pipeline]
      vars:
      - name: "SSH Private Key"
        description: "The SSH private key to access the instance where to install K3s."
        key: ssh_key
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - ssh
        type: string
        default: "((($ .organization_canonical $)-($ .project $)-($ .environment $)-compute-ssh.ssh_key))"
        required: true
