---
version: "2"
use_cases:
- name: default
  sections:
  - name: K3s
    groups:
    - name: SSH Key
      technologies: [pipeline]
      vars:
      - name: "SSH Private Key"
        description: "The SSH private key to access the instance where to install K3s."
        key: ssh_key
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - ssh
        type: string
        required: true
