---
# Configuration of the Cycloid stack
version: '4'
name: 'Nexus Repository'
canonical: 'stack-nexus-k8s-demo'
description: 'Deploys a Nexus Repository on a Kubernetes cluster using a Helm chart.'
author: 'Cycloid'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/nexus.png'
keywords:
- 'nexus'
- 'repository'
- 'artefact'
- 'provider:kubernetes'
technologies:
- technology: nexus
  version: "3.33"
- technology: terraform
  version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .config_root $)/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .config_root $)/terraform/main.tf'