---
version: "2"
use_cases:
- name: default
  sections:
  - name: Nexus Repository
    groups:
    - name: Pod specifications
      technologies: [terraform]
      vars:
      - name: "Disk size"
        unit: Go
        description: "Disk size for the Nexus Repository."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 10
            - 100
        required: true

    - name: Kubernetes Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Kubeconfig"
        description: "The Kubeconfig to access your Kubernetes Cluster."
        key: kubeconfig_content
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: (("custom_($ .organization_canonical $)-($ .project $)-($ .environment $)-kubeconfig.kubeconfig"))
        required: true