---
# Configuration of the Cycloid stack
version: '4'
name: 'MySQL Database'
canonical: stack-mysql
author: Cycloid
description: |
  Deploys a MySQL database on AWS RDS, Azure Database for MySQL, or Google Cloud SQL.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/mysql.svg
keywords:
  - mysql
  - database
  - rds
  - cloud sql
  - azure database
technologies:
- technology: terraform
  version: 1.8.3

config:
  aws:
    name: 'Amazon RDS for MySQL'
    description: 'Amazon Relational Database Service (Amazon RDS) for MySQL.'
    cloud_provider: aws
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/aws/main.tf'
        destination: '($ .config_root $)/terraform/aws/main.tf'

  azure:
    name: 'Azure Database for MySQL'
    description: 'Azure Database with Flexible Server for MySQL.'
    cloud_provider: azure
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/azure/main.tf'
        destination: '($ .config_root $)/terraform/azure/main.tf'

  gcp:
    name: 'Google Cloud SQL for MySQL'
    description: 'Google Cloud SQL managed MySQL database.'
    cloud_provider: gcp
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/gcp/main.tf'
        destination: '($ .config_root $)/terraform/gcp/main.tf' 