resource_types:
- name: terraform
  type: registry-image
  source:
    repository: cycloid/terraform-resource
    tag: ((terraform_version))


resources:
- name: tfstate
  type: terraform
  icon: terraform
  source:
    env_name: ($ .environment $)
    backend_type: http
    backend_config:
      address: '($ .api_url $)/inventory?jwt=($ .inventory_jwt $)'
    vars:
      github_pat: ((github_pat))
      cycloid_api_key: ((cycloid_api_key))
      cycloid_api_url: ($ .api_url $)
      cy_org: ($ .organization_canonical $)
      cy_pro: ($ .project $)
      cy_env: ($ .environment $)
      cy_com: ($ .component $)


# The Terraform stack (will be merged with the config)
- name: git_stack-terraform
  type: git
  icon: github-circle
  source:
    uri: ($ .scs_url $)
    branch: ($ .scs_branch $)
    ($- if eq .scs_cred_type "basic_auth" $)
    username: ((($ .scs_cred_path $).username))
    password: ((($ .scs_cred_path $).password))
    ($- end $)
    ($- if eq .scs_cred_type "ssh" $)
    private_key: ((($ .scs_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .stack_path $)/terraform/*

# The Terraform config (will be merged with the stack)
- name: git_config-terraform
  type: git
  icon: github-circle
  source:
    uri: ($ .cr_url $)
    branch: ($ .cr_branch $)
    ($- if eq .cr_cred_type "basic_auth" $)
    username: ((($ .cr_cred_path $).username))
    password: ((($ .cr_cred_path $).password))
    ($- end $)
    ($- if eq .cr_cred_type "ssh" $)
    private_key: ((($ .cr_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform/*

groups:
- name: overview
  jobs:
    - create-git-repo
    - scaffold-project

- name: destroy
  jobs:
    - destroy-git-repo


jobs:
  - name: create-git-repo
    serial: true
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - in_parallel:
        - get: git_stack-terraform
          trigger: true

        - get: git_config-terraform
          trigger: true

      - task: merge-stack-and-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /usr/bin/merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
          outputs:
          - name: merged-stack
            path: "merged-stack"
        params:
          CONFIG_PATH: ($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform
          STACK_PATH: ($ .stack_path $)/terraform

      - put: tfstate
        params:
          terraform_source: merged-stack/


  # Monitor new open PR to deploy feature env
  - name: scaffold-project
    max_in_flight: 1
    build_logs_to_retain: 20
    plan:
      - in_parallel:
        - get: tfstate
          trigger: true
          passed:
            - create-git-repo

      - task: copy-template
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: node
              tag: latest
          run:
            path: /bin/bash
            args:
            - -ecx
            - |
              apt-get update
              apt-get install jq -y
              mkdir -p ~/.ssh
              echo "${GIT_KEY}" >~/.ssh/git
              chmod 600 ~/.ssh/git
              eval "$(ssh-agent -s)"
              ssh-add ~/.ssh/git
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              git clone $GIT_URL template
              git clone ${GIT_SOURCE_URL} source
              rm -rf source/.git
              mv source/${GIT_SOURCE_PATH}/* template/
              mv source/${GIT_SOURCE_PATH}/.* template/
              cd template/
              git config --global user.email "devops@cycoid.io"
              git config --global user.name "Cycloid"
              git add .
              git commit -m "Initial commit"
              git push

              echo "Application build completed."
        params:
          GIT_URL: "git@github.com:cycloid-demo/($ .organization_canonical $)-($ .project $).git"
          GIT_SOURCE_URL: ((git_source_url))
          GIT_SOURCE_PATH: ((git_source_path))
          GIT_KEY: ((($ .organization_canonical $)-($ .project $)-($ .environment $)-git-ssh.ssh_key))
          PROJECT: ($ .project $)
          FEATURE_FLAGS: ((vuejs_feature_flags))


  # Destroy the infrastructure
  - name: destroy-git-repo
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - in_parallel:
        - get: git_stack-terraform
          trigger: false
        - get: git_config-terraform
          trigger: false
        - get: tfstate
          trigger: false

      - task: merge-stack-and-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /usr/bin/merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
          outputs:
          - name: merged-stack
            path: "merged-stack"
        params:
          CONFIG_PATH: ($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform
          STACK_PATH: ($ .stack_path $)/terraform

      - put: tfstate
        params:
          action: destroy
          terraform_source: merged-stack/
        get_params:
          action: destroy