---
- name: install applications
  hosts: all
  become: yes

  vars_files:
  - "environments/default.yml"
  - ["environments/node.yml", "environments/empty.yml"]

  tasks:
  - name: Service to Restart
    service:
      name: '{{ hosts_service }}'
      state: restarted

  - name: Package to Install
    apt:
      name: '{{ hosts_package }}'
      state: present
    when: (hosts_package is defined) and (hosts_package|length > 0)

  - name: User to Create
    user:
      name: '{{ hosts_user }}'
      shell: '/bin/bash'
      state: present
    when: (hosts_user is defined) and (hosts_user|length > 0)