---
version: "2"
use_cases:
- name: default
  sections:
  - name: Landing Zone
    groups:
    - name: Outscale
      technologies: [pipeline]
      vars:
      - name: "Outscale Account"
        description: "The Outscale account where to deploy the infrastructure."
        key: outscale_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: "((outscale))"
        required: true

      - name: "Outscale Region"
        description: "The Outscale region where to deploy the infrastructure."
        key: outscale_region
        widget: auto_complete
        type: string
        required: true
        default: "eu-west-2"
        values:
        - eu-west-2
        - cloudgouv-eu-west-1
        - us-east-2
        - us-west-1
        - ap-northeast-1

    - name: IONOS
      technologies: [pipeline]
      vars:
      - name: "IONOS Account"
        description: "The IONOS account where to deploy the infrastructure."
        key: ionos_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: "((ionos))"
        required: true

      - name: "IONOS Regions"
        description: "The IONOS region where to deploy the infrastructure."
        key: ionos_region
        widget: dropdown
        type: map
        required: false
        values:
        - {"label": "Frankfurt am Main (DE)", "value": "de/fra"}
        - {"label": "Karlsruhe (DE)", "value": "de/fkb"}
        - {"label": "Berlin (DE)", "value": "de/txl"}
        - {"label": "Paris (FR)", "value": "fr/par"}
        - {"label": "London (GB)", "value": "gb/lhr"}
        - {"label": "Logroño (ES)", "value": "es/vit"}
