---
version: "2"
use_cases:
- name: default
  sections:
  - name: config
    groups:
    - name: VueJS
      technologies: [pipeline]
      vars:
      - name: "Git Source Template"
        description: "Which source to use for the first commit. Either create a new VueJS application with npm or use an existing git repository."
        key: git_source
        widget: dropdown
        type: array
        required: true
        values:
        - {"label": "Generate a new VueJS project.", "value": "vuejs"}
        - {"label": "Copy an existing git repository.", "value": "git"}
    - name: Git Repository
      technologies: [pipeline]
      condition: "$git_source == 'git'"
      vars:
      - name: "Git Repository"
        description: "Git repository URL to copy for the first commit."
        key: git_source_url
        widget: simple_text
        type: string
        default: "https://github.com/cycloid-community-catalog/onboarding-scaffold.git"
        required: true
      - name: "Git Path"
        description: "Path in the Git repository to copy for the first commit."
        key: git_source_path
        widget: simple_text
        type: string
        default: "simple-counter"
        required: false
    - name: VueJS
      technologies: [pipeline]
      condition: "$git_source == 'vuejs'"
      vars:
      - name: "Feature flag to scaffold new Vue.js project"
        key: vuejs_feature_flags
        widget: dropdown
        type: array
        required: true
        values:
        - {"label": "default - Create a project with the default configuration without any additional features.", "value": "default"}
        - {"label": "typescript - Add TypeScript support.", "value": "typescript"}
        - {"label": "jsx - Add JSX support.", "value": "jsx"}
        - {"label": "vue-router - Add Vue Router for SPA development.", "value": "vue-router"}
        - {"label": "pinia - Add Pinia for state management.", "value": "pinia"}
        - {"label": "vitest - Add Vitest for unit testing.", "value": "vitest"}
        - {"label": "cypress - Add Cypress for end-to-end testing. If used without --vitest, it will also add Cypress Component Testing.", "value": "cypress"}
        - {"label": "playwright - Add Playwright for end-to-end testing.", "value": "playwright"}
        - {"label": "nightwatch - Add Nightwatch for end-to-end testing. If used without --vitest, it will also add Nightwatch Component Testing.", "value": "nightwatch"}
        - {"label": "eslint - Add ESLint for code quality.", "value": "eslint"}
        - {"label": "eslint-with-prettier - Add Prettier for code formatting in addition to ESLint.", "value": "eslint-with-prettier"}
        widget_config:
          multiselect: true
        validations:
          - array:
              max_elems: 4
            error_message: "4 feature flags can be selected at most."
      - name: "GitHub PAT"
        description: "GitHub Personal Access Token allowing to create the new code repository"
        key: github_pat
        widget: cy_cred
        widget_config:
          cred_types: ["custom"]
        type: string
        default: "((github-pat.key))"
        required: true

