---
# Configuration of the Cycloid stack
version: '4'
name: Azure Virtual Machine
canonical: stack-compute-azure-demo
author: Cycloid
description: |
  Deploys an Azure Virtual Machine using Terraform.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/azure-vm.png
keywords:
  - virtual machine
  - instance
  - provider:azure
technologies:
- technology: terraform
  version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform/main.tf'