---
version: "2"
use_cases:
- name: default
  sections:
  - name: Compute
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure credentials"
        description: "The azure credential used to deploy the infrastructure. It contains subscription_id, tenant_id, client_id, and client_secret."
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true

    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Instance type for the VM."
        key: vm_instance_type
        widget: slider_list
        type: string
        default: "Standard_DS2_v2"
        values:
            - "Standard_DS1_v2"
            - "Standard_DS2_v2"
            - "Standard_DS3_v2"
        required: true

      - name: "Disk size"
        unit: Go
        description: "Disk size for the VM."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 30
        values:
            - 30
            - 250
        required: true

      # - name: "Ingress TCP ports"
      #   description: "Ingress TCP ports allowed from the internet. Type any ports as needed."
      #   key: vm_ports_in
      #   widget: dropdown
      #   widget_config:
      #     multiselect: true
      #   type: array
      #   values: ["22","80","443","6443","8080"]
      #   default: ["22","80","443","6443"]
      #   required: false
      - name: "Ingress TCP ports"
        description: "Ingress TCP ports allowed from the internet. Type any ports as needed."
        key: vm_ports_in
        widget: text_area
        type: array
        default:
        - 22
        - 80
        - 443
        - 6443

      - name: "Create or Select Resource Group and VPC"
        description: "Whether to create a new Resource group and VPC or select existing ones."
        key: res_selector
        widget: dropdown
        type: map
        required: true
        default: "Create new"
        values:
        - {"label": "Create new", "value": "create"}
        - {"label": "Select from Asset Inventory", "value": "inventory"}
        - {"label": "Enter manually", "value": "manual"}

    - name: Create VNet and Resource Group
      technologies: [terraform]
      condition: '$res_selector == "Create new"'
      vars:
      - name: "Azure location"
        description: "Azure location where to create resources."
        key: azure_location
        widget: dropdown
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/azure-locations.json
        type: string
        required: true

    - name: Select from Asset Inventory
      technologies: [terraform]
      condition: '$res_selector == "Select from Asset Inventory"'
      vars:
      - name: "Existing Resource Group Name"
        description: "The name of the existing resource group where the resources will be deployed."
        key: resource_group_name_inventory
        widget: cy_inventory_resource
        widget_config:
          attribute: name
          filters:
            type: azurerm_resource_group
        type: string
        required: true
      - name: "Virtual Network"
        description: "Virtual Network where to deploy the resources. Make sure the VNet is in the same location as the previously selected resource group."
        key: vpc_name_inventory
        widget: cy_inventory_resource
        widget_config:
          attribute: name
          filters:
            type: azurerm_virtual_network
        type: string
        required: true

    - name: Enter manually
      technologies: [terraform]
      condition: '$res_selector == "Enter manually"'
      vars:
      - name: "Resource Group Name"
        description: "The name of the existing resource group where the resources will be deployed."
        key: resource_group_name_manual
        widget: simple_text
        type: string
        required: true
      - name: "Virtual Network Name"
        description: "Virtual Network name where the resources will be deployed. Make sure the VNet is in the same location as the previously selected resource group."
        key: vpc_name_manual
        widget: simple_text
        type: string
        required: true

    - name: Applications
      technologies: [pipeline]
      vars:
      - name: "Install K3s"
        description: "Whether to install K3s or not."
        key: install_k3s
        widget: switch
        type: boolean
        default: true
        required: true

    - name: Day-2 Operations
      technologies: [pipeline]
      vars:
      - name: "Instance status"
        description: "Status for the deployed instances."
        key: vm_instance_status
        widget: radios
        type: string
        default: "Started"
        values:
            - "Started"
            - "Stopped"
        required: true

      - name: "Destroy Timer"
        description: "The number of minutes to wait before automatically destroying the infrastructure after creation."
        key: destroy_timer_in_minutes
        widget: number
        type: integer
        default: 60
        required: true