---
# Configuration of the Cycloid stack
version: '4'
name: 'K3s'
canonical: stack-k3s-europe
author: Cycloid
description: |
  Deploy a K3s cluster on OVH or IONOS instance.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/kubernetes.png
keywords:
  - network
  - subnet
  - security
  - ovh
  - ionos
  - provider:ovh
  - provider:ionos
technologies:
- technology: terraform
  version: 1.8.3

config:
  ovh:
    name: 'OVH'
    description: 'Deploy a K3s cluster on OVH instance'
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/ovh/main.tf'
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform/ovh/main.tf'

  ionos:
    name: 'IONOS'
    description: 'Deploy a IONOS cluster on OVH instance'
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/ionos/main.tf'
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform/ionos/main.tf'