---
# Configuration of the Cycloid stack
version: '4'
name: 'K3s'
canonical: stack-k3s-europe
author: Cycloid
description: |
  Deploy a K3s cluster with NGINX as ingress controller on Outscale or IONOS instances.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/kubernetes.png
keywords:
  - kubernetes
  - outscale
  - ionos
  - provider:outscale
  - provider:ionos
technologies:
- technology: terraform
  version: 1.8.3

config:
  outscale:
    name: 'Outscale'
    description: 'Deploy a K3s cluster on Outscale instances.'
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/outscale/main.tf'
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform/outscale/main.tf'

  ionos:
    name: 'IONOS'
    description: 'Deploy a K3s cluster on IONOS instances.'
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/ionos/main.tf'
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform/ionos/main.tf'