---
version: "2"
use_cases:
- name: ovh
  sections:
  - name: K3s cluster
    groups:
    - name: OVH Access
      technologies: [pipeline]
      vars:
      - name: "OVH Account"
        description: "The OVH account where to deploy the infrastructure."
        key: ovh_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: "((ovh))"
        required: true

      - name: "OVH Region"
        description: "The OVH region where to deploy the infrastructure."
        key: ovh_region
        widget: dropdown
        type: map
        required: true
        values:
        - {"label": "Beauharnois BHS5 (FR)", "value": "BHS5"}
        - {"label": "Frankfurt DE1 (DE)", "value": "DE1"}
        - {"label": "Gravelines GRA11 (FR)", "value": "GRA11"}
        - {"label": "London UK1 (GB)", "value": "UK1"}
        - {"label": "Milan EU-SOUTH-LZ-MIL-A (IT)", "value": "EU-SOUTH-LZ-MIL-A"}
        - {"label": "Roubaix RBX-A (FR)", "value": "RBX-A"}
        - {"label": "Stockholm EU-NORTH-LZ-STO-A (SE)", "value": "EU-NORTH-LZ-STO-A"}
        - {"label": "Strasbourg SBG5 (FR)", "value": "SBG5"}
        - {"label": "Warsaw WAW1 (PL)", "value": "WAW1"}

    - name: OVH Infrastructure
      technologies: [terraform]
      vars:
      - name: "OVH Compute Flavor"
        description: "The OVH compute flavor to deploy."
        key: ovh_flavor_name
        widget: dropdown
        type: map
        required: true
        values:
        - {"label": "b3-8	(2 vCore / 8 Gb)", "value": "b3-8"}
        - {"label": "b3-16	(4 vCore / 16 Gb)", "value": "b3-16"}
        - {"label": "c2-7	(2 vCore / 7 Gb)", "value": "c2-7"}
        - {"label": "c3-4	(2 vCore / 4 Gb)", "value": "c3-4"}
        - {"label": "c3-8	(2 vCore / 8 Gb)", "value": "c3-8"}
        - {"label": "d2-2	(1 vCore / 2 Gb)", "value": "d2-2"}
        - {"label": "d2-4	(1 vCore / 4 Gb)", "value": "d2-4"}
        - {"label": "r2-15	(2 vCore / 15 Gb)", "value": "r2-15"}
        - {"label": "r3-16	(2 vCore / 16 Gb)", "value": "r3-16"}


- name: ionos
  sections:
  - name: K3s cluster
    groups:
    - name: IONOS Access
      technologies: [pipeline]
      vars:
      - name: "IONOS Account"
        description: "The IONOS account where to deploy the infrastructure."
        key: ionos_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: "((ionos))"
        required: true

      - name: "IONOS Region"
        description: "The IONOS region where to deploy the infrastructure."
        key: ionos_region
        widget: dropdown
        type: map
        required: true
        values:
        - {"label": "Frankfurt am Main (DE)", "value": "de/fra"}
        - {"label": "Karlsruhe (DE)", "value": "de/fkb"}
        - {"label": "Berlin (DE)", "value": "de/txl"}
        - {"label": "Paris (FR)", "value": "fr/par"}
        - {"label": "London (GB)", "value": "gb/lhr"}
        - {"label": "Logroño (ES)", "value": "es/vit"}

    - name: IONOS Infrastructure
      technologies: [terraform]
      vars:
      - name: "IONOS Compute Configuration"
        description: "The IONOS cube configuration to deploy."
        key: ionos_cube
        widget: dropdown
        type: string
        required: true
        values:
        - "Basic Cube XS"
        - "Basic Cube S"
        - "Basic Cube M"
        - "Basic Cube L"
        - "Basic Cube XL"
        - "Memory Cube S"
        - "Memory Cube M"
        - "Memory Cube L"
        - "Memory Cube XL"