---
# Configuration of the Cycloid stack
version: '4'
name: Compute Instance
canonical: stack-compute-gcp-demo
author: Cycloid
description: |
  Deploys a GCP Virtual Machine using Terraform.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/gcp-vm.png
keywords:
  - virtual machine
  - instance
  - provider:gcp
technologies:
- technology: terraform
  version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .org $)/($ .project $)/($ .env $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .org $)/($ .project $)/($ .env $)/($ .component $)/terraform/main.tf'